import createClient from 'openapi-fetch'
import type { paths } from './generated/api-types' // autogenerated in package.json

export const { GET, POST, PUT, DELETE, PATCH } = createClient<paths>({
  baseUrl: import.meta.env.VITE_CORE_API_URL || 'http://localhost:5010',
  headers: {
    'Content-Type': 'application/json',
  },
})

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string
  ) {
    super(message)
    this.name = 'ApiError'
  }
}
