import createClient, { Middleware } from 'openapi-fetch'
import axios from 'axios'

import type { paths } from './generated/core-api-types' // autogenerated in package.json

import { config } from '../config'
import { logger } from 'onecore-utilities'

let token: string | null = null

type Params = {
  refresh: boolean
}

export const client = createClient<paths>({
  baseUrl: config.CORE__API_URL,
  headers: {
    'Content-Type': 'application/json',
  },
})

export async function getCoreAccessToken(params: Params = { refresh: false }) {
  if (token && !params.refresh) {
    return token
  }

  const response = await axios.post<{ token: string }>(
    `${config.CORE__API_URL}/auth/generatetoken`,
    {
      username: config.CORE__USERNAME,
      password: config.CORE__PASSWORD,
    },
  )

  if (!response.data.token) {
    throw new Error('Failed to get Core API token')
  }

  return response.data.token
}
const authMiddleware: Middleware = {
  async onRequest({ request }) {
    try {
      token = await getCoreAccessToken()
      request.headers.set('Authorization', `Bearer ${token}`)
      return request
    } catch (error) {
      logger.error({ error }, 'Failed to authenticate with Core API')
      throw new CoreApiError(500, 'Failed to authenticate with Core API')
    }
  },
  async onResponse({ response, request }) {
    if (response.status === 401) {
      logger.info('Got 401 from Core, refreshing token')
      token = await getCoreAccessToken({ refresh: true })
      request.headers.set('Authorization', `Bearer ${token}`)
      return fetch(request)
    }

    return response
  },
}

client.use(authMiddleware)

class CoreApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message)
    this.name = 'HttpError'
  }
}
