import createClient from 'openapi-fetch'
import type { paths } from './generated/api-types' // autogenerated in package.json

// In production, use the /api path which will be proxied by nginx
// In development, we use the vite proxy to forward requests to the backend
const API_BASE_URL = '/api'

export const { GET, POST, PUT, DELETE, PATCH } = createClient<paths>({
  baseUrl: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
})

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string
  ) {
    super(message)
    this.name = 'ApiError'
  }
}
