name: Build and Push Images

on:
  push:
    branches:
      - main
      - feat/k8s
    tags:
      - production*
      - staging*

jobs:
  # lint-and-test:
  #   uses: ./.github/workflows/lint-and-test.yml

  version:
    runs-on: ubuntu-latest
    #needs: lint-and-test
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Update version
        id: version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [[ $GITHUB_REF == refs/tags/production* ]]; then
            npm version major
          elif [[ $GITHUB_REF == refs/tags/staging* ]]; then
            npm version minor
          else
            npm version patch
          fi
          echo "version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
          git push origin main --follow-tags

  build-and-push:
    needs: version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [property-base, property-tree]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.package }}
          tags: |
            type=raw,value=${{ needs.version.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/${{ matrix.package }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.package }}
          cache-to: type=gha,mode=max,scope=${{ matrix.package }}
