name: Build and Push Images

on:
  push:
    branches:
      - main
    tags:
      - production*
      - staging*

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  prepare-version:
    needs: [lint]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      bump_type: ${{ steps.bump.outputs.type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump type
        id: bump
        run: |
          if [[ $GITHUB_REF == refs/tags/production* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/staging* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Get current version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [property-base, property-tree]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.package }}
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.prepare-version.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/${{ matrix.package }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.package }}
          cache-to: type=gha,mode=max,scope=${{ matrix.package }}

  commit-version:
    needs: [build-and-push, prepare-version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update version
        run: |
          # Let npm handle version bump, commit, and tag creation
          npm version ${{ needs.prepare-version.outputs.bump_type }} -m "chore: bump version to %s [skip ci]"
          git push --follow-tags
